### ISSUE TITLE
binstar groups raises exception

### ISSUE THREAD

**Issue by bkreider** [Anaconda-Platform/anaconda-client#124]
```
bradleys-mbp-2:conda_cluster bkreider$ binstar groups
/opt/anaconda/lib/python2.7/site-packages/pytz/__init__.py:29: UserWarning: Module argparse was already imported from /opt/anaconda/lib/python2.7/argparse.pyc, but /opt/anaconda/lib/python2.7/site-packages is being added to sys.path
  from pkg_resources import resource_stream
Traceback (most recent call last):
  File "/opt/anaconda/bin/binstar", line 6, in <module>
    sys.exit(main())
  File "/Users/bkreider/src/binstar_client/binstar_client/scripts/cli.py", line 60, in main
    return args.main(args)
  File "/Users/bkreider/src/binstar_client/binstar_client/commands/groups.py", line 75, in main
    raise NotImplementedError(args.action)
NotImplementedError: None
```

**Comment by goanpeca** [comment]
This seems to be no longer an issue

```
0316-gpena-castellanos:anaconda-fusion gpena-castellanos$ anaconda groups
usage: anaconda groups [-h] [--perms {read,write,admin}]
                       {add,show,members,add_member,remove_member,packages,add_package,remove_package}
                       spec
anaconda groups: error: the following arguments are required: action, spec
