### ISSUE TITLE
OSError: [Errno 40] Message too long when uploading PyPI package [py34]

### ISSUE THREAD

**Issue by malev** [Anaconda-Platform/anaconda-client#126]
When following the [binstar's guide](http://docs.binstar.org/examples.html#UploadingAPypiPackage). I have this error:

```
(temp3.4)➜  pypi git:(master) binstar upload dist/test_package34-0.3.1.tar.gz
Using binstar api site https://api.binstar.org
detecting package type ...
pypi
extracting package attributes for upload ...
[BinstarError] Trouble reading metadata from 'dist/test_package34-0.3.1.tar.gz'. Is this a valid pypi package
--- Logging error ---
Traceback (most recent call last):
  File "/Users/mvanetta/miniconda3/envs/temp3.4/lib/python3.4/logging/handlers.py", line 899, in emit
    self.socket.send(msg)
OSError: [Errno 40] Message too long

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mvanetta/miniconda3/envs/temp3.4/lib/python3.4/logging/handlers.py", line 903, in emit
    self.socket.send(msg)
OSError: [Errno 40] Message too long
Call stack:
  File "/Users/mvanetta/miniconda3/envs/temp3.4/lib/python3.4/site-packages/clyent/logs/__init__.py", line 13, in excepthook
    logger.error('', exc_info=exc_info)
Message: ''
Arguments: ()
(temp3.4)➜  pypi git:(master)
```

This is my `conda info`:

```
Current conda install:

             platform : osx-64
        conda version : 3.9.1
  conda-build version : 1.10.2
       python version : 3.4.2.final.0
     requests version : 2.5.3
     root environment : /Users/mvanetta/miniconda3  (writable)
  default environment : /Users/mvanetta/miniconda3/envs/temp3.4
     envs directories : /Users/mvanetta/miniconda3/envs
        package cache : /Users/mvanetta/miniconda3/pkgs
         channel URLs : https://conda.binstar.org/sean/osx-64/
                        https://conda.binstar.org/sean/noarch/
                        https://conda.binstar.org/javascript/osx-64/
                        https://conda.binstar.org/javascript/noarch/
                        http://repo.continuum.io/pkgs/free/osx-64/
                        http://repo.continuum.io/pkgs/free/noarch/
                        http://repo.continuum.io/pkgs/pro/osx-64/
                        http://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/mvanetta/.condarc
    is foreign system : False
```

Note that I'm on **python 3.4**

**Comment by goanpeca** [comment]
This was fixed
