### ISSUE TITLE
Binstar should display user-friendly error message when unable to contact server

### ISSUE THREAD

**Issue by tswicegood** [Anaconda-Platform/anaconda-client#131]
Attempting to login on Windows 8 via Powershell or CMD, and I receive the following traceback after entering my password:

```
PS C:\Users\builder> binstar login
Using binstar api site https://api.binstar.org
Username: tswicegood
tswicegood's Password:
[ConnectionError] ('Connection aborted.', gaierror(11001, 'getaddrinfo failed'))
Traceback (most recent call last):
  File "C:\Users\builder\Miniconda\Scripts\binstar-script.py", line 9, in <module>
    load_entry_point('binstar==0.10.1', 'console_scripts', 'binstar')()
  File "C:\Users\builder\Miniconda\lib\site-packages\binstar_client\scripts\cli.py", line 94, in main
    description=__doc__, version=version)
  File "C:\Users\builder\Miniconda\lib\site-packages\binstar_client\scripts\cli.py", line 76, in binstar_main
    return args.main(args)
  File "C:\Users\builder\Miniconda\lib\site-packages\binstar_client\commands\login.py", line 92, in main
    interactive_login(args)
  File "C:\Users\builder\Miniconda\lib\site-packages\binstar_client\commands\login.py", line 87, in interactive_login
    token = interactive_get_token(args)
  File "C:\Users\builder\Miniconda\lib\site-packages\binstar_client\commands\login.py", line 57, in interactive_get_token
    hostname=hostname)
  File "C:\Users\builder\Miniconda\lib\site-packages\binstar_client\__init__.py", line 88, in authenticate
    res = self.session.post(url, auth=(username, password), data=data, headers=headers)
  File "C:\Users\builder\Miniconda\lib\site-packages\requests\sessions.py", line 504, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\builder\Miniconda\lib\site-packages\requests\sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\builder\Miniconda\lib\site-packages\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\builder\Miniconda\lib\site-packages\requests\adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(11001, 'getaddrinfo failed'))
```

This is binstar 0.10.1.  I've tried both the conda installed and pip installed flavors.  Neither works.

**Comment by tswicegood** [comment]
This may be a firewall setting on this new VM.  I'm unable to even hit `https://api.binstar.org/` via `requests.get` in a Python console.  Looking to see if there's any settings I need to enable.

**Comment by tswicegood** [comment]
I was able to clone data from GitHub and am able to ping various known hosts (google, bing, yahoo, etc.).  For some reason I'm just unable to see binstar.org or api.binstar.org from CMD or Powershell.  I *can* load them both in Google Chrome, however.

**Comment by tswicegood** [comment]
Ok.  I disabled all firewalls in Windows 8 but that didn't solve the problem.  I restarted and applied the updates and it appears to have gone away.  I'm leaving this as a `bug` as the user should never see a traceback, but adding `enhancement` as this should also display a message that `binstar` is unable to connect to the server.

**Comment by j0hn** [comment]
anaconda command fails with the following error:

`[NotFound] API server not found. Please check your API url configuration.`
