### ISSUE TITLE
binstar package --list-collaborators option broken

### ISSUE THREAD

**Issue by LilaHickey** [Anaconda-Platform/anaconda-client#153]
binstar package --list-collaborators <user>/<package-name>
Using binstar api site http:/api.binstar.rog
:Collaborators:
[NameError] global name 'binstar' is not defined
Traceback (most recent call last):
File "/auto/foopen/CONDA/bin/binstar", line 6, in <module>
sys.exit(main())
File "/auto/foopen/CONDA/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 94, in main
description=doc_, version=version)
File "/auto/foopen/CONDA/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 76, in binstar_main
return args.main(args)
File "/auto/foopen/CONDA/lib/python2.7/site-packages/binstar_client/commands/package.py", line 24, in main
for collab in binstar.package_collaborators(owner, package):
NameError: global name 'binstar' is not defined

**Comment by goanpeca** [comment]
This has been fixed already
