### ISSUE TITLE
Handle DNS errors gracefully for invalid hostnames

### ISSUE THREAD

**Issue by bkreider** [Anaconda-Platform/anaconda-client#207]
When configuring the client for enterprise AS installs, it raises a stack trace on invalid hostnames instead of a nice message:

```
(client)bradleys-mbp-2:binstar bkreider$ anaconda login
Using binstar api site https://asdfasdfasdfasdfadsf.demo.continuum.io/api
Username: user1
user1's Password: 
https://asdfasdfasdfasdfadsf.demo.continuum.io/api/authentications
[ConnectionError] ('Connection aborted.', gaierror(8, 'nodename nor servname provided, or not known')) 
Traceback (most recent call last):
  File "/opt/anaconda/envs/client/bin/anaconda", line 6, in <module>
    sys.exit(main())
  File "/opt/anaconda/envs/client/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 94, in main
    description=__doc__, version=version)
  File "/opt/anaconda/envs/client/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 76, in binstar_main
    return args.main(args)
  File "/opt/anaconda/envs/client/lib/python2.7/site-packages/binstar_client/commands/login.py", line 93, in main
    interactive_login(args)
  File "/opt/anaconda/envs/client/lib/python2.7/site-packages/binstar_client/commands/login.py", line 88, in interactive_login
    token = interactive_get_token(args)
  File "/opt/anaconda/envs/client/lib/python2.7/site-packages/binstar_client/commands/login.py", line 57, in interactive_get_token
    hostname=hostname)
  File "/opt/anaconda/envs/client/lib/python2.7/site-packages/binstar_client/__init__.py", line 88, in authenticate
    res = self.session.post(url, auth=(username, password), data=data, headers=headers)
  File "/opt/anaconda/envs/client/lib/python2.7/site-packages/requests/sessions.py", line 508, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/opt/anaconda/envs/client/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/anaconda/envs/client/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/opt/anaconda/envs/client/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(8, 'nodename nor servname provided, or not known'))
```

**Comment by srossross** [comment]
This is a great idea. Lets bump this to high priority because it should be easy to fix.
