### ISSUE TITLE
Troubleshooting argument number issue with "anaconda -h"

### ISSUE THREAD

**Issue by davidlmobley** [Anaconda-Platform/anaconda-client#331]
I'm in python2.7 and in my normal conda environment, I'm getting this issue after just installing `anaconda-client` and `anaconda-build` for the first time via conda:

```
$ anaconda -h
Traceback (most recent call last):
  File "/Users/dmobley/anaconda/bin/anaconda", line 6, in <module>
    sys.exit(binstar_client.scripts.cli.main())
  File "/Users/dmobley/anaconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 87, in main
    description=__doc__, version=version)
  File "/Users/dmobley/anaconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 51, in binstar_main
    add_subparser_modules(parser, sub_command_module, 'conda_server.subcommand')
TypeError: add_subparser_modules() takes exactly 2 arguments (3 given)
```

Creating a new conda python 2.7 test environment and freshly installing there resolves the issue, so it's something in my package list, but I don't know how to troubleshoot. Any tips? My `conda list` is below:

```
$ conda list
# packages in environment at /Users/dmobley/anaconda:
#
_license                  1.1                      py27_0    <unknown>
abstract-rendering        0.5.1                np19py27_0    <unknown>
alabaster                 0.7.6                    py27_0    defaults
alchemical-analysis       1.0.2.dev0                <pip>
alchemical-setup          1.0.2.dev0                <pip>
ambermini                 15.0.4                        1    http://conda.binstar.org/omnia/osx-64/ambermini-15.0.4-1.tar.bz2
anaconda                  2.2.0                np19py27_0    <unknown>
anaconda-build            1.15.0                   py27_0    defaults
anaconda-client           1.4.0                    py27_0    defaults
appnope                   0.1.0                    py27_0    defaults
appscript                 1.0.1                    py27_0    <unknown>
argcomplete               0.8.4                    py27_0    <unknown>
astropy                   1.0.1                np19py27_0    <unknown>
babel                     2.1.1                    py27_0    defaults
backports                 1.0                      py27_0    defaults
backports.shutil-get-terminal-size 1.0.0                     <pip>
backports.ssl-match-hostname 3.4.0.2                   <pip>
bcolz                     0.8.1                np19py27_0    <unknown>
beautiful-soup            4.3.2                    py27_0    <unknown>
beautifulsoup4            4.3.2                     <pip>
biopython                 1.65                 np19py27_0    defaults
bitarray                  0.8.1                    py27_0    <unknown>
blaze                     0.7.3                     <pip>
blaze-core                0.7.3                np19py27_0    <unknown>
blz                       0.6.2                np19py27_0    <unknown>
bokeh                     0.8.1                np19py27_1    <unknown>
boost                     1.56.0                   py27_3    https://conda.binstar.org/nividic/osx-64/boost-1.56.0-py27_3.tar.bz2
boto                      2.36.0                   py27_0    <unknown>
bzip2                     1.0.6                         3    defaults
cdecimal                  2.3                      py27_0    <unknown>
certifi                   14.05.14                 py27_0    <unknown>
cffi                      0.9.2                    py27_0    <unknown>
cloog                     0.18.0                        0    defaults
clyent                    0.3.4                    py27_0    <unknown>
cmake                     3.0.1                         0    defaults
colorama                  0.3.3                    py27_0    <unknown>
conda                     4.0.8                    py27_0    defaults
conda-build               1.11.0                   py27_0    <unknown>
conda-env                 2.4.5                    py27_0    defaults
configobj                 5.0.6                    py27_0    <unknown>
configparser              3.5.0b2                  py27_1    defaults
cryptography              0.8                      py27_0    <unknown>
curl                      7.45.0                        0    defaults
cycler                    0.9.0                    py27_0    defaults
cython                    0.22                     py27_0    <unknown>
cytoolz                   0.7.2                    py27_0    <unknown>
datashape                 0.4.4                np19py27_1    <unknown>
decorator                 4.0.4                    py27_0    defaults
docutils                  0.12                     py27_0    <unknown>
dynd-python               0.6.5                np19py27_0    <unknown>
entrypoints               0.2                      py27_1    defaults
enum34                    1.0.4                    py27_0    <unknown>
fastcache                 1.0.2                    py27_0    <unknown>
feedparser                5.2.1                    py27_0    defaults
fftw3f                    3.3.4                         2    http://conda.binstar.org/omnia/osx-64/fftw3f-3.3.4-2.tar.bz2
flask                     0.10.1                   py27_1    <unknown>
freetype                  2.5.5                         0    defaults
funcsigs                  0.4                      py27_0    <unknown>
futures                   2.2.0                    py27_0    <unknown>
gaff2xml                  0.6.2                    py27_0    http://conda.binstar.org/omnia/osx-64/gaff2xml-0.6.2-py27_0.tar.bz2
gcc                       4.8.5                         3    defaults
get_terminal_size         1.0.0                    py27_0    defaults
gevent                    1.0.1                    py27_0    <unknown>
gevent-websocket          0.9.3                    py27_0    <unknown>
gmp                       5.1.2                         6    defaults
greenlet                  0.4.5                    py27_0    <unknown>
griddataformats           0.3.0                     <pip>
grin                      1.2.1                    py27_1    <unknown>
gromacswrapper            0.3.3                     <pip>
h5py                      2.4.0                np19py27_0    <unknown>
hdf5                      1.8.15.1                      2    defaults
ipykernel                 4.1.0                    py27_0    defaults
ipython                   4.2.0                    py27_1    defaults
ipython-genutils          0.1.0                     <pip>
ipython-notebook          4.0.4                    py27_0    defaults
ipython-qtconsole         3.0.0                    py27_0    <unknown>
ipython_genutils          0.1.0                    py27_0    defaults
ipywidgets                4.1.1                    py27_0    defaults
isl                       0.12.2                        1    defaults
itsdangerous              0.24                     py27_0    <unknown>
jdcal                     1.0                      py27_0    <unknown>
jedi                      0.8.1                    py27_0    <unknown>
jinja2                    2.8                      py27_0    defaults
jpeg                      8d                            1    <unknown>
jsonschema                2.4.0                    py27_0    <unknown>
jupyter                   1.0.0                    py27_2    defaults
jupyter-client            4.2.2                     <pip>
jupyter-console           4.1.1                     <pip>
jupyter-core              4.1.0                     <pip>
jupyter_client            4.2.2                    py27_0    defaults
jupyter_console           4.1.1                    py27_0    defaults
jupyter_core              4.1.0                    py27_0    defaults
launcher                  1.0.0                         2    <unknown>
libcpptraj                4.3.1                         0    https://conda.binstar.org/ambermd/osx-64/libcpptraj-4.3.1-0.tar.bz2
libdynd                   0.6.5                         0    <unknown>
libnetcdf                 4.3.3.1                       3    defaults
libpng                    1.6.17                        0    defaults
libsodium                 0.4.5                         0    <unknown>
libtiff                   4.0.2                         1    <unknown>
libxml2                   2.9.0                         1    <unknown>
libxslt                   1.1.28                        2    <unknown>
llvmlite                  0.2.2                    py27_1    <unknown>
lxml                      3.4.2                    py27_0    <unknown>
markupsafe                0.23                     py27_0    <unknown>
matplotlib                1.5.1               np110py27_0    defaults
mdanalysis                0.12.1.dev0               <pip>
mdtraj                    1.7.2               np110py27_0    http://conda.binstar.org/omnia/osx-64/mdtraj-1.7.2-np110py27_0.tar.bz2
mdtraj-dev                1.1.X                np19py27_0    http://conda.binstar.org/omnia/osx-64/mdtraj-dev-1.1.X-np19py27_0.tar.bz2
mistune                   0.5.1                    py27_0    <unknown>
mkl                       11.3.1                        0    defaults
mock                      1.0.1                    py27_0    <unknown>
mpc                       1.0.1                         0    defaults
mpfr                      3.1.2                         0    defaults
multipledispatch          0.4.7                    py27_0    <unknown>
nbconvert                 4.2.0                    py27_0    defaults
nbformat                  4.0.1                    py27_0    defaults
networkx                  1.10                     py27_0    defaults
nglview                   0.4+195.g7d8ec46           <pip>
nltk                      3.0.2                np19py27_0    <unknown>
node-webkit               0.10.1                        0    <unknown>
nose                      1.3.4                    py27_1    <unknown>
notebook                  4.2.0                    py27_0    defaults
numba                     0.17.0               np19py27_0    <unknown>
numexpr                   2.4.6               np110py27_1    defaults
numpy                     1.10.4                   py27_0    defaults
numpydoc                  0.5                      py27_1    defaults
odo                       0.3.1                np19py27_0    <unknown>
openeye                   2015.2.3                  <pip>
openeye-python2.7-osx-10.10-x64 2015.2.3                  <pip>
openeye-toolkits          2016.2.1                  <pip>
openeye-toolkits-python2.7-osx-10.10-x64 2016.2.1                  <pip>
openmm                    7.0rc1                   py27_1    http://conda.binstar.org/omnia/osx-64/openmm-7.0rc1-py27_1.tar.bz2
openmm-dev                0.0.0                    py27_0    http://conda.binstar.org/omnia/osx-64/openmm-dev-0.0.0-py27_0.tar.bz2
openmoltools              0.7.0                    py27_1    https://conda.binstar.org/omnia/osx-64/openmoltools-0.7.0-py27_1.tar.bz2
openpyxl                  1.8.5                    py27_0    <unknown>
openssl                   1.0.2g                        0    defaults
packmol                   1.0.0                         0    http://conda.binstar.org/omnia/osx-64/packmol-1.0.0-0.tar.bz2
pandas                    0.18.0              np110py27_0    defaults
parmed                    2.5.1                    py27_0    http://conda.binstar.org/omnia/osx-64/parmed-2.5.1-py27_0.tar.bz2
parmed-dev                0.0.0                    py27_0    http://conda.binstar.org/omnia/osx-64/parmed-dev-0.0.0-py27_0.tar.bz2
path.py                   8.2.1                    py27_0    defaults
patsy                     0.3.0                np19py27_0    <unknown>
pep8                      1.6.2                    py27_0    <unknown>
pexpect                   3.3                      py27_0    defaults
pickleshare               0.5                      py27_0    defaults
pillow                    2.7.0                    py27_1    <unknown>
pip                       8.1.1                    py27_0    defaults
ply                       3.4                      py27_0    <unknown>
psutil                    2.2.1                    py27_0    <unknown>
ptyprocess                0.4                      py27_0    <unknown>
pubchempy                 1.0.3                     <pip>
py                        1.4.26                   py27_0    <unknown>
pyasn1                    0.1.7                    py27_0    <unknown>
pyaudio                   0.2.7                    py27_0    <unknown>
pycosat                   0.6.1                    py27_0    <unknown>
pycparser                 2.10                     py27_0    <unknown>
pycrypto                  2.6.1                    py27_0    <unknown>
pycurl                    7.19.5.1                 py27_0    <unknown>
pyflakes                  0.8.1                    py27_0    <unknown>
pygments                  2.0.2                    py27_0    <unknown>
pymbar                    2.1beta0             np19py27_0    http://conda.binstar.org/omnia/osx-64/pymbar-2.1beta0-np19py27_0.tar.bz2
pyopenssl                 0.14                     py27_0    <unknown>
pyparsing                 2.0.3                    py27_0    <unknown>
pyqt                      4.11.4                   py27_1    defaults
pytables                  3.2.2               np110py27_0    defaults
pytest                    2.6.4                    py27_0    <unknown>
python                    2.7.11                        0    defaults
python-dateutil           2.5.0                    py27_0    defaults
python.app                1.2                      py27_3    <unknown>
pytraj                    1.0.6                    py27_0    https://conda.binstar.org/ambermd/osx-64/pytraj-1.0.6-py27_0.tar.bz2
pytz                      2016.1                   py27_0    defaults
pyxb                      1.2.4                    py27_0    http://conda.binstar.org/omnia/osx-64/pyxb-1.2.4-py27_0.tar.bz2
pyyaml                    3.11                     py27_1    defaults
pyzmq                     14.5.0                   py27_0    <unknown>
qt                        4.8.7                         1    defaults
qtconsole                 4.2.1                    py27_0    defaults
rdkit                     2016.03.1           np110py27_0    https://conda.binstar.org/nividic/osx-64/rdkit-2016.03.1-np110py27_0.tar.bz2
readline                  6.2                           2    <unknown>
redis                     2.6.9                         0    <unknown>
redis-py                  2.10.3                   py27_0    <unknown>
requests                  2.9.1                    py27_0    defaults
rope                      0.9.4                    py27_1    <unknown>
runipy                    0.1.3                    py27_0    <unknown>
scikit-image              0.11.2               np19py27_0    <unknown>
scikit-learn              0.16.1              np110py27_0    defaults
scipy                     0.17.0              np110py27_0    defaults
scripttest                1.3                      py27_0    http://conda.binstar.org/omnia/osx-64/scripttest-1.3-py27_0.tar.bz2
seaborn                   0.7.0                    py27_0    defaults
setuptools                20.7.0                   py27_0    defaults
sigfig                    0.1                       <pip>
simplegeneric             0.8.1                    py27_0    defaults
sip                       4.16.9                   py27_0    defaults
six                       1.10.0                   py27_0    defaults
snowballstemmer           1.2.0                    py27_0    defaults
sockjs-tornado            1.0.1                    py27_0    <unknown>
solvationtoolkit          0.4.0.dev0                <pip>
sphinx                    1.3.1                    py27_0    defaults
sphinx-rtd-theme          0.1.7                     <pip>
sphinx_rtd_theme          0.1.7                    py27_0    defaults
spyder                    2.3.4                    py27_1    <unknown>
spyder-app                2.3.4                    py27_0    <unknown>
sqlalchemy                0.9.9                    py27_0    <unknown>
sqlite                    3.9.2                         0    defaults
ssl_match_hostname        3.4.0.2                  py27_0    <unknown>
statsmodels               0.6.1                np19py27_0    <unknown>
sympy                     0.7.6                    py27_0    <unknown>
tables                    3.2.2                     <pip>
terminado                 0.5                      py27_0    <unknown>
thermopyl                 1.0.0                    py27_0    https://conda.binstar.org/choderalab/osx-64/thermopyl-1.0.0-py27_0.tar.bz2
tk                        8.5.18                        0    <unknown>
toolz                     0.7.1                    py27_0    <unknown>
tornado                   4.1                      py27_0    <unknown>
traitlets                 4.2.1                    py27_0    defaults
ujson                     1.33                     py27_0    <unknown>
uncertainties             2.4.7.1                   <pip>
unicodecsv                0.9.4                    py27_0    <unknown>
werkzeug                  0.10.1                   py27_0    <unknown>
wheel                     0.29.0                   py27_0    defaults
xlrd                      0.9.3                    py27_0    <unknown>
xlsxwriter                0.6.7                    py27_0    <unknown>
xlwings                   0.3.4                    py27_0    <unknown>
xlwt                      0.7.5                    py27_0    <unknown>
yaml                      0.1.6                         0    defaults
zeromq                    4.0.4                         0    <unknown>
zlib                      1.2.8                         0    <unknown>
```

**Comment by dsludwig** [comment]
It looks like you have quite an old version of one of the dependent libraries:

```
clyent                    0.3.4                    py27_0    <unknown>
```

The latest release is https://github.com/Anaconda-Platform/clyent/releases/tag/1.2.2. You should be able to upgrade using `conda update clyent`.

I will also make sure that the requirements of the next version of anaconda-client specify a newer version.

Thanks for the report, @davidlmobley!
