### ISSUE TITLE
Error handling issue

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Platform/anaconda-client#335]
Had an interesting error crop up recently. See the traceback below and this related issue ( https://github.com/conda-forge/gmpy2-feedstock/issues/1 ) for more details.

```
Traceback (most recent call last):
  File "/opt/conda/bin/anaconda", line 6, in <module>
    sys.exit(binstar_client.scripts.cli.main())
  File "/opt/conda/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 87, in main
    description=__doc__, version=version)
  File "/opt/conda/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 66, in binstar_main
    return args.main(args)
  File "/opt/conda/lib/python3.5/site-packages/binstar_client/commands/upload.py", line 219, in main
    except requests_ext.OpenSslError:
TypeError: catching classes that do not inherit from BaseException is not allowed
```

**Comment by goanpeca** [comment]
@jakirkham is this still an issue?
