### ISSUE TITLE
TypeError when uploading package

### ISSUE THREAD

**Issue by koverholt** [Anaconda-Platform/anaconda-client#370]
I'm getting the following error when uploading a package.

The initial upload works:

```
$ /home/travis/miniconda/bin/anaconda -t [redacted] upload /home/travis/miniconda/conda-bld/linux-64/adam-enterprise-notebooks-4.2.1-py27_2.tar.bz2 /home/travis/miniconda/conda-bld/osx-64/adam-enterprise-notebooks-4.2.1-py27_2.tar.bz2 --label dev
Using Anaconda API: https://api.anaconda.org
detecting package type ...
conda
extracting package attributes for upload ...
done
Uploading file anaconda-adam/adam-enterprise-notebooks/4.2.1/linux-64/adam-enterprise-notebooks-4.2.1-py27_2.tar.bz2 ... 
 uploaded 12 of 12Kb: 100.00% ETA: 0.0 minutes
Upload(s) Complete
detecting package type ...
conda
extracting package attributes for upload ...
done
Uploading file anaconda-adam/adam-enterprise-notebooks/4.2.1/osx-64/adam-enterprise-notebooks-4.2.1-py27_2.tar.bz2 ... 
 uploaded 12 of 12Kb: 100.00% ETA: 0.0 minutes
Upload(s) Complete
Package located at:
https://anaconda.org/anaconda-adam/adam-enterprise-notebooks
Package located at:
https://anaconda.org/anaconda-adam/adam-enterprise-notebooks
```

But the next upload fails (only difference is that it's built with Python 3.4 vs. Python 2.7).

```
$ /home/travis/miniconda/bin/anaconda -t [redacted] upload /home/travis/miniconda/conda-bld/linux-64/adam-enterprise-notebooks-4.2.1-py34_2.tar.bz2 /home/travis/miniconda/conda-bld/osx-64/adam-enterprise-notebooks-4.2.1-py34_2.tar.bz2 --label dev

Using Anaconda API: https://api.anaconda.org
detecting package type ...
conda
extracting package attributes for upload ...
done
Uploading file anaconda-adam/adam-enterprise-notebooks/4.2.1/linux-64/adam-enterprise-notebooks-4.2.1-py34_2.tar.bz2 ... 
 uploaded 12 of 12Kb: 100.00% ETA: 0.0 minutes
[ERROR] 
Traceback (most recent call last):
  File "/home/travis/miniconda/lib/python3.5/site-packages/binstar_client/commands/upload.py", line 196, in upload_package
    callback=upload_print_callback(args))
  File "/home/travis/miniconda/lib/python3.5/site-packages/binstar_client/__init__.py", line 510, in upload
    self._check_response(res)
  File "/home/travis/miniconda/lib/python3.5/site-packages/binstar_client/__init__.py", line 200, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.BinstarError: ('Method Not Allowed: Specified method is invalid for this resource. ([POST] https://api.anaconda.org/commit/anaconda-adam/adam-enterprise-notebooks/4.2.1/linux-64/adam-enterprise-notebooks-4.2.1-py34_2.tar.bz2 -> 405)', 405)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/miniconda/bin/anaconda", line 6, in <module>
    sys.exit(binstar_client.scripts.cli.main())
  File "/home/travis/miniconda/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 87, in main
    description=__doc__, version=version)
  File "/home/travis/miniconda/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 66, in binstar_main
    return args.main(args)
  File "/home/travis/miniconda/lib/python3.5/site-packages/binstar_client/commands/upload.py", line 244, in main
    args=args))
  File "/home/travis/miniconda/lib/python3.5/site-packages/binstar_client/commands/upload.py", line 202, in upload_package
    except requests_ext.OpenSslError:
TypeError: catching classes that do not inherit from BaseException is not allowed
```

**Comment by koverholt** [comment]
This seems to be working now in the latest version.
