### ISSUE TITLE
pprint issue

### ISSUE THREAD

**Issue by FelipeCalliari** [Anaconda-Platform/anaconda-client#380]
When I do:

```
C:\> anaconda search -t conda ggplot
```

I get this:

```
Using Anaconda API: https://api.anaconda.org
Run 'anaconda show <USER/PACKAGE>' to get more details:
Packages:
     Name                      |  Version | Package Types   | Platforms
     ------------------------- |   ------ | --------------- | ---------------
     ActivisionGameScience/ggplot |    0.6.8 | conda           | linux-64
                                          : ggplot for python
[ERROR]
Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\anaconda-script.py", line 5, in <module>
    sys.exit(binstar_client.scripts.cli.main())
  File "C:\Anaconda2\lib\site-packages\binstar_client\scripts\cli.py", line 88, in main
    description=__doc__, version=version)
  File "C:\Anaconda2\lib\site-packages\binstar_client\scripts\cli.py", line 66, in binstar_main
    return args.main(args)
  File "C:\Anaconda2\lib\site-packages\binstar_client\commands\search.py", line 15, in search
    pprint_packages(packages, access=False)
  File "C:\Anaconda2\lib\site-packages\binstar_client\utils\pprint.py", line 70, in pprint_packages
    pprint_package(package, access, full_name, revision=revisions)
  File "C:\Anaconda2\lib\site-packages\binstar_client\utils\pprint.py", line 34, in pprint_package
    package['conda_platforms'] = ', '.join(package['conda_platforms'])
TypeError: sequence item 1: expected string or Unicode, NoneType found
```

This issue was already reported by @jimsrc in (https://github.com/ContinuumIO/anaconda-issues/issues/1308) but he may have used an older version of anaconda-client since he used:

```
$ binstar --show-traceback search -t conda cython
```

**Even if it is not the best solution..**

The problem can be easily solved by editting this file:

```
[anaconda_path]\lib\site-packages\binstar_client\utils\pprint.py
```

**Original**
line34: ```package['conda_platforms'] = ', '.join(package['conda_platforms'])```

**Modified**
line34: ``if package['conda_platforms'].count(None):``
line35: ``    package['conda_platforms'].remove(None)``
line36: ``package['conda_platforms'] = ', '.join(package['conda_platforms'])``

**Comment by bioruffo** [comment]
Line 39 of pprint.py also uses `.join` on `package['package_types']`. I wonder if this could also break in some cases?

    if package.get('package_types'):
        package['package_types'] = ', '.join(noNones(package['package_types']))

So just to avoid risks, on my machine I did this:  

    def noNones(mylist):
        return [str(x) for x in mylist if x is not None]

and:

    33 if 'conda_platforms' in package:
    34    package['conda_platforms'] = ', '.join(noNones(package['conda_platforms']))
    35 if not full_name:
    36     package['full_name'] = package['name']
    37 package['access'] = 'published' if package.get('published') else 'public' if package['public'] else 'private'
    38 if package.get('package_types'):
    39     package['package_types'] = ', '.join(noNones(package['package_types']))
