### ISSUE TITLE
Trouble build 1.6.2 on Windows

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Platform/anaconda-client#398]
Ran into some issues building `anaconda-client` 1.6.2 on Windows Python 2 and 3 at conda-forge. The traceback from one of the Python 3 builds is shown below. The Python 2 traceback differs by being a `WindowsError` instead. Links to the PR and AppVeyor builds are below.

```python
import: 'binstar_client'
Traceback (most recent call last):
  File "C:\bld\anaconda-client_1489510578565\_t_env\lib\site-packages\binstar_client\utils\conda.py", line 38, in get_conda_root
    conda_root = _import_conda_root()
  File "C:\bld\anaconda-client_1489510578565\_t_env\lib\site-packages\binstar_client\utils\conda.py", line 16, in _import_conda_root
    import conda.config
ImportError: No module named 'conda'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\bld\anaconda-client_1489510578565\test_tmp\run_test.py", line 2, in <module>
    import binstar_client
  File "C:\bld\anaconda-client_1489510578565\_t_env\lib\site-packages\binstar_client\__init__.py", line 14, in <module>
    from .utils import compute_hash, jencode, pv
  File "C:\bld\anaconda-client_1489510578565\_t_env\lib\site-packages\binstar_client\utils\__init__.py", line 15, in <module>
    from .config import (get_server_api, get_binstar, dirs,
  File "C:\bld\anaconda-client_1489510578565\_t_env\lib\site-packages\binstar_client\utils\config.py", line 22, in <module>
    from binstar_client.utils.conda import CONDA_PREFIX, CONDA_ROOT
  File "C:\bld\anaconda-client_1489510578565\_t_env\lib\site-packages\binstar_client\utils\conda.py", line 52, in <module>
    CONDA_ROOT = get_conda_root()
  File "C:\bld\anaconda-client_1489510578565\_t_env\lib\site-packages\binstar_client\utils\conda.py", line 48, in get_conda_root
    conda_root = _conda_root_from_conda_info()
  File "C:\bld\anaconda-client_1489510578565\_t_env\lib\site-packages\binstar_client\utils\conda.py", line 22, in _conda_root_from_conda_info
    output = subprocess.check_output([CONDA_EXE, 'info', '--json']).decode("utf-8")
  File "C:\bld\anaconda-client_1489510578565\_t_env\lib\subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "C:\bld\anaconda-client_1489510578565\_t_env\lib\subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\bld\anaconda-client_1489510578565\_t_env\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "C:\bld\anaconda-client_1489510578565\_t_env\lib\subprocess.py", line 955, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
(C:\bld\anaconda-client_1489510578565\_t_env) C:\bld\anaconda-client_1489510578565\test_tmp>if errorlevel 1 exit 1 
```

xref: https://github.com/conda-forge/anaconda-client-feedstock/pull/6
ref: https://ci.appveyor.com/project/conda-forge/anaconda-client-feedstock/build/1.0.12

cc @msarahan

**Comment by jakirkham** [comment]
Any thoughts on this?

**Comment by damianavila** [comment]
ping @dsludwig, I have seen this as well...

**Comment by j0hn** [comment]
I'm looking into this. Apparently what's causing this is that instead of having a `conda.exe` file there's a `conda.bat` which works as a symlink. I'll change it so it looks for any of those two.

**Comment by j0hn** [comment]
I just merged a fix for this, should be fixed on the next release. Will try to release soon.

**Comment by damianavila** [comment]
ping @jakirkham

**Comment by damianavila** [comment]
Thanks @j0hn !!

**Comment by j0hn** [comment]
@jakirkham 1.6.3 release is done, you can go ahead and try to build your own `anaconda-client`. We'll be uploading a build to anaconda cloud as soon as possible. Thanks for the bug report!

**Comment by damianavila** [comment]
Thanks for the update @j0hn.
