### ISSUE TITLE
pywintypes CSIDL_COMMON_APPDATA error

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Platform/anaconda-client#399]
Ran into a rather strange issue trying to build a new package for `conda-build-all` at conda-forge. Talked to @msarahan about it and he seemed to think the use of the `CSIDL` path is a problem. Details in this [comment]( https://github.com/conda-forge/conda-build-all-feedstock/pull/28#issuecomment-286474137 ). Have included the traceback I'm seeing below. A link to the PR with the recipe and a link to the AppVeyor builds are below. This is showing up on Python 2.7, 3.5, and 3.6 on Windows. Tried to rebuild `anaconda-client` in the hope that it would fix the issue, but instead ran into issue ( https://github.com/Anaconda-Platform/anaconda-client/issues/398 ).

```python
Traceback (most recent call last):
  File "C:\bld\conda-build-all_1489513005711\_t_env\Scripts\conda-build-all-script.py", line 3, in <module>
    import conda_build_all.cli
  File "C:\bld\conda-build-all_1489513005711\_t_env\lib\site-packages\conda_build_all\cli.py", line 8, in <module>
    import conda_build_all.builder
  File "C:\bld\conda-build-all_1489513005711\_t_env\lib\site-packages\conda_build_all\builder.py", line 20, in <module>
    from binstar_client.utils import get_binstar
  File "C:\bld\conda-build-all_1489513005711\_t_env\lib\site-packages\binstar_client\__init__.py", line 14, in <module>
    from .utils import compute_hash, jencode, pv
  File "C:\bld\conda-build-all_1489513005711\_t_env\lib\site-packages\binstar_client\utils\__init__.py", line 153, in <module>
    SITE_CONFIG = join(dirs.site_data_dir, 'config.yaml')
  File "C:\bld\conda-build-all_1489513005711\_t_env\lib\site-packages\binstar_client\utils\appdirs.py", line 250, in site_data_dir
    version=self.version)
  File "C:\bld\conda-build-all_1489513005711\_t_env\lib\site-packages\binstar_client\utils\appdirs.py", line 107, in site_data_dir
    path = os.path.join(_get_win_folder("CSIDL_COMMON_APPDATA"),
  File "C:\bld\conda-build-all_1489513005711\_t_env\lib\site-packages\binstar_client\utils\appdirs.py", line 285, in _get_win_folder_with_pywin32
    dir = shell.SHGetFolderPath(0, getattr(shellcon, csidl_name), 0, 0)
pywintypes.com_error: (-2147024893, 'The system cannot find the path specified.', None, None)
(C:\bld\conda-build-all_1489513005711\_t_env) C:\bld\conda-build-all_1489513005711\test_tmp>if errorlevel 1 exit 1
```

xref: https://github.com/conda-forge/conda-build-all-feedstock/pull/28
ref: https://ci.appveyor.com/project/conda-forge/conda-build-all-feedstock/build/1.0.59

**Comment by jakirkham** [comment]
Any thoughts on this?

**Comment by goanpeca** [comment]
@jakirkham is this still an issue?
