### ISSUE TITLE
Failed to upload to Anaconda Cloud

### ISSUE THREAD

**Issue by hans-permana** [Anaconda-Platform/anaconda-client#473]
I was initially made aware of this issue when the [Travis build](https://travis-ci.org/CCI-Tools/cate-conda) of [this project](https://github.com/CCI-Tools/cate-conda) failed because the upload to Anaconda Cloud failed. 

And then, I tried it manually in my Ubuntu VM to first build the conda package, and then upload it using anaconda upload. 
```
$ anaconda -v -t <anaconda_token> upload ~/miniconda3/conda-bld/linux-64/cate-cli-2.0.0.dev10-py36_0.tar.bz2 -u ccitools
Using Anaconda API: https://api.anaconda.org
[DEBUG] Using token from command line args
Using "ccitools" as upload username
Detecting file type...
[DEBUG] Testing if conda package ..
[DEBUG] This is a conda package
File type is "conda"
Extracting package attributes for upload
Creating package "cate-cli"
Creating release "2.0.0.dev10"
Uploading file "ccitools/cate-cli/2.0.0.dev10/linux-64/cate-cli-2.0.0.dev10-py36_0.tar.bz2"
```

At a glance it looked as if it was successful (no errors or warnings). However, the package was not really uploaded. I could not find it in [Anaconda Cloud](https://anaconda.org/ccitools/cate-cli/files). 

Any idea what is happening here?

**Comment by hans-permana** [comment]
After a bit more digging and putting more debugging, we found out that the actual exception is

```
Traceback (most recent call last):
  File "/home/hans/miniconda3/lib/python3.6/site-packages/anaconda_client-1.6.13+5.g0f7a39c.dirty-py3.6.egg/binstar_client/commands/upload.py", line 242, in upload_package
    channels=args.labels, callback=upload_print_callback(args))
  File "/home/hans/miniconda3/lib/python3.6/site-packages/anaconda_client-1.6.13+5.g0f7a39c.dirty-py3.6.egg/binstar_client/__init__.py", line 533, in upload
    self._check_response(res)
  File "/home/hans/miniconda3/lib/python3.6/site-packages/anaconda_client-1.6.13+5.g0f7a39c.dirty-py3.6.egg/binstar_client/__init__.py", line 230, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.BinstarError: ('Forbidden: Request forbidden -- authorization will not help ([POST] https://api.anaconda.org/stage/ccitools/cate-cli/2.0.0.dev11/linux-64/cate-cli-2.0.0.dev11-py36_0.tar.bz2 -> 403)', 403)
```

Actually we have two problems here:
1. That Anaconda silently fails without handling the error correctly by showing the error message to users
2. The error `Forbidden: Request forbidden -- authorization will not help ([POST] https://api.anaconda.org/stage/ccitools/cate-cli/2.0.0.dev11/linux-64/cate-cli-2.0.0.dev11-py36_0.tar.bz2 -> 403` which we don't know what causes this. **Note**: this is reproducible on MacOS and Linux. On Windows (based on our AppVeyor build), we don't seem to have this issue.

**Comment by hans-permana** [comment]
I used the following dependencies:
```
conda: 4.5.3
conda-build: 3.10.2
anaconda-client: 1.6.14
python: 3.6.4
```

**Comment by hans-permana** [comment]
the second issue was solved by removing the _**app**_ section in the recipe. It would be nice if an explicit message is returned instead of just 403 error.

**Comment by hdoupe** [comment]
@hans-permana I'm running into a similar issue. How did you get the stack-trace you give in this [comment](https://github.com/Anaconda-Platform/anaconda-client/issues/473#issuecomment-389455635)?

**Comment by hans-permana** [comment]
@hdoupe , I modified the try-except block in binstar_client/commands/upload.py [line 236](https://github.com/Anaconda-Platform/anaconda-client/blob/develop/binstar_client/commands/upload.py#L236):
```python
        try:
            upload_info = aserver_api.upload(username, package_name, version, file_attrs['basename'], fd,
                                             binstar_package_type, args.description,
                                             dependencies=file_attrs.get('dependencies'), attrs=file_attrs['attrs'],
                                             channels=args.labels, callback=upload_print_callback(args))
        except BaseException:
            # logger.info('Distribution already exists. Please use the -i/--interactive or --force options or `anaconda '
            #             'remove %s/%s/%s/%s', username, package_name, version, file_attrs['basename'])
            # logger.info('error uploading: ', errors)
            import sys
            logger.error('error uploading: ', exc_info=sys.exc_info())

            raise
```
