### ISSUE TITLE
BUG: conflict error when copying package to a label where it doesn't exist

### ISSUE THREAD

**Issue by astrofrog** [Anaconda-Platform/anaconda-client#500]
(This is different from #455 but motivated by the same use case)

I have a channel, ``glueviz``, which has a package ``win-32/fast-histogram-0.4-py36_0.tar.bz2`` which is tagged with the ``main`` label. I want to copy over the package so that it is also in the ``dev`` label. Therefore, I tried:

```
api.copy('conda-forge', 'fast-histogram', '0.4', basename='win-32/fast-histogram-0.4-py36_0.tar.bz2', to_owner='glueviz', from_label='main', to_label='dev')
```

But I get the following error:

```
Traceback (most recent call last):
  File "sync.py", line 73, in <module>
    main(*sys.argv)
  File "sync.py", line 70, in main
    from_label=args.source_label, to_label=args.destination_label)
  File "sync.py", line 48, in sync
    to_owner=to_channel, from_label=from_label, to_label=to_label)
  File "/Users/tom/miniconda3/envs/dev/lib/python3.6/site-packages/binstar_client/mixins/package.py", line 19, in copy
    self._check_response(res)
  File "/Users/tom/miniconda3/envs/dev/lib/python3.6/site-packages/binstar_client/__init__.py", line 230, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.Conflict: ('', 409)
```

Is there fundamentally no way to solve my use case at the moment?

**Comment by mhsmith** [comment]
There's some discussion in #351 of how to use the CLI to add a label to an existing package *without* removing its existing labels. It looks like this wasn't implemented at that time, and I still can't work out any way to do it with anaconda-client version 1.12.2:

```console
$ anaconda copy --to-owner chaquo --to-label pypi-7.0 chaquo/tensorflow-gpu/2.1.0
Using Anaconda API: https://api.anaconda.org
[ERROR] File conflict while copying! Try to use --replace or --update options for force copying
```

`--update` does not add the requested label:
```console
1$ anaconda copy --to-owner chaquo --to-label pypi-7.0 --update chaquo/tensorflow-gpu/2.1.0
Using Anaconda API: https://api.anaconda.org
Copied file: tensorflow_gpu-2.1.0-9-py3-none-any.whl
Copied 1 files! 
NOTE: copy command with --update option doesn`t copy already existing files. Try to use --replace to overwrite existing data
```

`--replace` does add the label, but also removes all existing labels. And if you pass multiple `--to-label` arguments, they're all ignored except for the last one.
