### ISSUE TITLE
binstar_client.errors.ServerError: ('Internal server error', 500) while anaconda copying a package

### ISSUE THREAD

**Issue by srezepin** [Anaconda-Platform/anaconda-client#505]
Hi,

When I'm trying to copy anaconda package from one username to another (from ODSP-TEST to IzODA), I have the following error:
```
(root) 09:55:25 TSSKR@RS12 ~ anaconda --show-traceback copy ODSP-TEST/anaconda/1.1.0/zos-z/anaconda-1.1.0-8.tar.bz2 --to-owner IzODA
Using Anaconda Cloud api site https://api.anaconda.org
[ERROR]
Traceback (most recent call last):
  File "/rsusr/ported/IBM/izoda/anaconda/bin/anaconda", line 6, in <module>
    sys.exit(binstar_client.scripts.cli.main())
  File "/rsusr/ported/IBM/izoda/anaconda/lib/python3.6/site-packages/binstar_client/scripts/cli.py", line 87, in main
    description=__doc__, version=version)
  File "/rsusr/ported/IBM/izoda/anaconda/lib/python3.6/site-packages/binstar_client/scripts/cli.py", line 66, in binstar_main
    return args.main(args)
  File "/rsusr/ported/IBM/izoda/anaconda/lib/python3.6/site-packages/binstar_client/commands/copy.py", line 31, in main
    to_owner=args.to_owner, from_channel=from_label, to_channel=to_label)
  File "/rsusr/ported/IBM/izoda/anaconda/lib/python3.6/site-packages/binstar_client/mixins/package.py", line 19, in copy
    self._check_response(res)
  File "/rsusr/ported/IBM/izoda/anaconda/lib/python3.6/site-packages/binstar_client/__init__.py", line 164, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.ServerError: ('Internal server error', 500)
```
I also tried to run this command on another system, but there is the same result:
```
(newenv) srezepin@amsdevzosykl01:~$ anaconda --show-traceback copy ODSP-TEST/autotag/0.5/zos-z/autotag-0.5-6.tar.bz2 --to-owner IzODA
Using Anaconda API: https://api.anaconda.org
[ERROR]
Traceback (most recent call last):
  File "/home/srezepin/anaconda3/envs/newup/bin/anaconda", line 11, in <module>
    sys.exit(main())
  File "/home/srezepin/anaconda3/envs/newup/lib/python3.7/site-packages/binstar_client/scripts/cli.py", line 160, in main
    description=__doc__, version=version)
  File "/home/srezepin/anaconda3/envs/newup/lib/python3.7/site-packages/binstar_client/scripts/cli.py", line 139, in binstar_main
    return args.main(args)
  File "/home/srezepin/anaconda3/envs/newup/lib/python3.7/site-packages/binstar_client/commands/copy.py", line 32, in main
    to_owner=args.to_owner, from_label=from_label, to_label=to_label
  File "/home/srezepin/anaconda3/envs/newup/lib/python3.7/site-packages/binstar_client/mixins/package.py", line 19, in copy
    self._check_response(res)
  File "/home/srezepin/anaconda3/envs/newup/lib/python3.7/site-packages/binstar_client/__init__.py", line 230, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.ServerError: ('Internal server error', 500)
```

```
(root) 10:00:34 TSSKR@RS12 ~ anaconda auth -l
Using Anaconda Cloud api site https://api.anaconda.org

ID                        | Application                         | Remote Addr          | Host                      | Expires In      | Scopes
--------------------------+-------------------------------------+----------------------+---------------------------+-----------------+--------------------------
5c014eb089a6f38805ac107a  | binstar_client:TSSKR@RS12           | 2620:117:0:e:244:0:0:6 | RS12                      | 364 days        | api:modify-group
                          |                                     |                      |                           |                 | api:read
                          |                                     |                      |                           |                 | api:write
                          |                                     |                      |                           |                 | kapsel:upload
                          |                                     |                      |                           |                 | pypi:download
                          |                                     |                      |                           |                 | pypi:upload
```

```
(root) 10:19:22 TSSKR@RS12 ~ anaconda whoami
Using Anaconda Cloud api site https://api.anaconda.org
Username: srezepin
Member since: Tue Nov 27 13:19:17 2018
  +company: Rocket Software
  +description:
  +location:
  +name:
  +url:
  +user_type: user
```

Thanks.

**Comment by zorts** [comment]
I am in the "owner" group for the IzODA channel, and have been trying to make it possible for Sergey to upload packages. Initially the group was configured for read/write access, but I didn't realize that I had to add package access to the group, too. I did that, and it still didn't work. I then gave the group admin privileges and had Sergey log out and back in and try again - still no go.
