### ISSUE TITLE
conda update failed on macair

### ISSUE THREAD

**Issue by drschenk** [Anaconda-Platform/anaconda-client#601]
currently on macOS 10.15.7 in miniconda3 version 4.12.0

when I run:  conda update -n base conda

or  conda update -n base -c conda-forge conda

I get:

same garbage. (including conda activate):

(base) MBA-PSchenk-20:~ root# conda update -n base -c conda-forge conda
Collecting package metadata (current_repodata.json): failed
WARNING conda.exceptions:print_unexpected_error_report(1216): KeyError('pkgs_dirs')
Traceback (most recent call last):
File "/opt/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1082, in call
return func(*args, **kwargs)
File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 87, in _main
exit_code = do_call(args, p)
File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 84, in do_call
return getattr(module, func_name)(args, parser)
File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main_update.py", line 20, in execute
install(args, parser, 'update')
File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 264, in install
should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 155, in solve_for_transaction
should_retry_solve)
File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 196, in solve_for_diff
force_remove, should_retry_solve)
File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 300, in solve_final_state
ssc = self._collect_all_metadata(ssc)
File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
return f(*args, **kwds)
File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 435, in _collect_all_metadata
_supplement_index_with_system(virtual_pkg_index)
File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 159, in _supplement_index_with_system
cuda_version = context.cuda_version
File "/opt/miniconda3/lib/python3.7/site-packages/conda/auxlib/decorators.py", line 268, in new_fget
cache[inner_attname] = func(self)
File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/decorators.py", line 24, in wrapper
return func(*args, **kwargs)
File "/opt/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 895, in cuda_version
return cuda_detect()
File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/cuda.py", line 37, in cuda_detect
import ctypes
File "/opt/miniconda3/lib/python3.7/ctypes/init.py", line 7, in 
from _ctypes import Union, Structure, Array
ImportError: dlopen(/opt/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
Referenced from: /opt/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1214, in print_unexpected_error_report
message_builder.append(get_main_info_str(error_report['conda_info']))
File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 237, in get_main_info_str
info_dict['_' + key] = ('\n' + 26 * ' ').join(info_dict[key])
KeyError: 'pkgs_dirs'

>>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1082, in __call__
    return func(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 87, in _main
    exit_code = do_call(args, p)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 84, in do_call
    return getattr(module, func_name)(args, parser)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/main_update.py", line 20, in execute
    install(args, parser, 'update')
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 264, in install
    should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 155, in solve_for_transaction
    should_retry_solve)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 196, in solve_for_diff
    force_remove, should_retry_solve)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 300, in solve_final_state
    ssc = self._collect_all_metadata(ssc)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 435, in _collect_all_metadata
    _supplement_index_with_system(virtual_pkg_index)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 159, in _supplement_index_with_system
    cuda_version = context.cuda_version
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/auxlib/decorators.py", line 268, in new_fget
    cache[inner_attname] = func(self)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/decorators.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 895, in cuda_version
    return cuda_detect()
  File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/cuda.py", line 37, in cuda_detect
    import ctypes
  File "/opt/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/opt/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
  Referenced from: /opt/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
  Reason: image not found
$ /opt/miniconda3/bin/conda update -n base -c conda-forge conda

environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

**Comment by drschenk** [comment]
hello?

**Comment by drschenk** [comment]
fixed
