### ISSUE TITLE
CONDA_ROOT environment variable required for clean anaconda-client python3.9 virtual env on windows 

### ISSUE THREAD

**Issue by baleland** [Anaconda-Platform/anaconda-client#636]
VENV> conda install anaconda-client
VENV> anaconda -h

`Traceback (most recent call last):
  File "c:\Users\bleland\work\Spr2023\conda310_cli\Scripts\anaconda-script.py", line 6, in <module>
    from binstar_client.scripts.cli import main
  File "c:\Users\bleland\work\Spr2023\conda310_cli\lib\site-packages\binstar_client\__init__.py", line 21, in <module>
    from .mixins.channels import ChannelsMixin
  File "c:\Users\bleland\work\Spr2023\conda310_cli\lib\site-packages\binstar_client\mixins\channels.py", line 7, in <module>
    from binstar_client.utils import jencode
  File "c:\Users\bleland\work\Spr2023\conda310_cli\lib\site-packages\binstar_client\utils\__init__.py", line 14, in <module>
    from .config import (get_server_api, dirs, load_token, store_token,
  File "c:\Users\bleland\work\Spr2023\conda310_cli\lib\site-packages\binstar_client\utils\config.py", line 92, in <module>
    SITE_CONFIG = os.path.join(os.environ.get('CONDA_ROOT', CONDA_ROOT), 'etc', 'anaconda-client', 'config.yaml')
  File "c:\Users\bleland\work\Spr2023\conda310_cli\lib\ntpath.py", line 104, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
`

**Comment by matthewfeickert** [comment]
This happens with `micromamba` as well with [`anaconda-client` `v1.11.3`](https://github.com/Anaconda-Platform/anaconda-client/releases/tag/1.11.3)

```console
$ docker run --rm -ti mambaorg/micromamba:1.4.9-bullseye-slim /bin/bash
(base) mambauser@a9fd4835fb54:/tmp$ micromamba --version
1.4.9
(base) mambauser@a9fd4835fb54:/tmp$ micromamba install --quiet --channel conda-forge --yes "anaconda-client==1.11.3"
(base) mambauser@a9fd4835fb54:/tmp$ micromamba list | grep anaconda-client
  anaconda-client            1.11.3    pyhd8ed1ab_0        conda-forge
(base) mambauser@a9fd4835fb54:/tmp$ anaconda --help
Traceback (most recent call last):
  File "/opt/conda/bin/anaconda", line 6, in <module>
    from binstar_client.scripts.cli import main
  File "/opt/conda/lib/python3.11/site-packages/binstar_client/__init__.py", line 23, in <module>
    from .mixins.channels import ChannelsMixin
  File "/opt/conda/lib/python3.11/site-packages/binstar_client/mixins/channels.py", line 9, in <module>
    from binstar_client.utils import jencode
  File "/opt/conda/lib/python3.11/site-packages/binstar_client/utils/__init__.py", line 14, in <module>
    from .config import (get_server_api, dirs, load_token, store_token,
  File "/opt/conda/lib/python3.11/site-packages/binstar_client/utils/config.py", line 85, in <module>
    SITE_CONFIG = os.path.join(os.environ.get('CONDA_ROOT', CONDA_ROOT), 'etc', 'anaconda-client', 'config.yaml')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType
(base) mambauser@a9fd4835fb54:/tmp$
```

So this is still a problem.

However, https://github.com/mamba-org/setup-micromamba obviously works, so this must be (currently) fixable.

Thought @mattkram?

**Comment by matthewfeickert** [comment]
This can be [worked around](https://github.com/mamba-org/setup-micromamba/blob/b32aa2f553b477ad9a893d15410ef8ab51d5a7ef/action.yml#L80-L83) by manually setting the `CONDA_ROOT` environmental variable

```console
export CONDA_ROOT="$(readlink -f $(command -v micromamba))"
```

```console
(base) mambauser@a9fd4835fb54:/tmp$ anaconda --help
usage: anaconda [-h] [--disable-ssl-warnings] [--show-traceback] [-v] [-q] [-V] [-t TOKEN] [-s SITE]  ...

Anaconda repository command line manager

options:
  -h, --help            show this help message and exit
  -V, --version         show program's version number and exit

output:
  --disable-ssl-warnings
                        Disable SSL warnings (default: False)
  --show-traceback      Show the full traceback for chalmers user errors (default: False)
  -v, --verbose         print debug information on the console
  -q, --quiet           Only show warnings or errors on the console

anaconda-client options:
  -t TOKEN, --token TOKEN
                        Authentication token to use. May be a token or a path to a file containing a token
  -s SITE, --site SITE  select the anaconda-client site to use

Commands:
  
    auth                Manage Authorization Tokens
    label               Manage your Anaconda repository labels
    channel             [DEPRECATED in favor of label] Manage your Anaconda repository channels
    config              Anaconda client configuration
    copy                Copy packages from one account to another
    download            Download notebooks from your Anaconda repository
    groups              Manage Groups
    login               Authenticate a user
    logout              Log out from your Anaconda repository
    move                Move packages between labels
    notebook            Interact with notebooks in your Anaconda repository
    package             Package utils
    remove              Remove an object from your Anaconda repository. Must refer to the formal package name as it appears in the URL of the package. Also use anaconda show
                        <USERNAME> to see list of package names. Example: anaconda remove continuumio/empty-example-notebook
    search              Search in your Anaconda repository
    show                Show information about an object
    upload              Upload packages to your Anaconda repository
    whoami              Print the information of the current user
(base) mambauser@a9fd4835fb54:/tmp$
```

**Comment by mattkram** [comment]
@matthewfeickert I believe this should be fixed in the upcoming v1.12.0 release. The fix was merged from #667

There is a release candidate you might be able to try to confirm: `conda install anaconda-client-test=1.12.0rc1`

**Comment by matthewfeickert** [comment]
> There is a release candidate you might be able to try to confirm: `conda install anaconda-client-test=1.12.0rc1`

@mattkram what channel is `anaconda-client-test` on? For `micromamba` you need to specify a channel and it apparently isn't on `conda-forge`

```
(base) mambauser@e623b54e69b1:/tmp$ micromamba install --channel conda-forge --yes "anaconda-client-test=1.12.0rc1"
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
error    libmamba Could not solve for environment specs
    The following package could not be installed
    └─ anaconda-client-test 1.12.0rc1**  does not exist (perhaps a typo or a missing channel).
critical libmamba Could not solve for environment specs
```

and doesn't show up when searching `anaconda.org`: https://anaconda.org/search?q=anaconda-client-test

**Comment by mattkram** [comment]
@matthewfeickert I'm sorry, I totally mis-typed that.

https://anaconda.org/anaconda-client-test/anaconda-client

`conda install anaconda-client-test:: anaconda-client=1.12.0rc1`

I'll be on vacation next week, and I'm not on the team that is in charge of release, but I'll tag a few folks in case you need any further help or find the fix in #667 doesn't resolve your issue.

CC: @jjhelmus @AlbertDeFusco

**Comment by matthewfeickert** [comment]
Thanks @mattkram. Enjoy your holiday! :)

@jjhelmus @AlbertDeFusco :wave:

This isn't a problem on `conda` as `CONDA_ROOT` is already set, but if you're working in something like `micromamba` then by default that is not set correctly (c.f. https://github.com/scientific-python/upload-nightly-action/pull/23) (at least in the Docker images). The release candidate also fails to be installed given missing dependencies on other channels:

```console
$ docker run --rm -ti mambaorg/micromamba:1.4.9-bullseye-slim /bin/bash
(base) mambauser@81f4548a846f:/tmp$ micromamba install --quiet --channel anaconda-client-test --yes "anaconda-client=1.12.0rc1"
error    libmamba Could not solve for environment specs
    The following package could not be installed
    └─ anaconda-client 1.12.0rc1**  is not installable because it requires
       └─ clyent >=1.2.0 , which does not exist (perhaps a missing channel).
critical libmamba Could not solve for environment specs
(base) mambauser@81f4548a846f:/tmp$
```

**Comment by AlbertDeFusco** [comment]
Interesting. clyent 1.2.2 is available from conda-forge and defaults

https://anaconda.org/search?q=clyent

Do you have other channels configured for mamba to work from?

**Comment by matthewfeickert** [comment]
> Interesting. clyent 1.2.2 is available from conda-forge and defaults
> 
> https://anaconda.org/search?q=clyent

Okay, then with that bit of information then yes this now works

```console
$ docker run --rm -ti mambaorg/micromamba:1.4.9-bullseye-slim /bin/bas
(base) mambauser@4999fa799ae3:/tmp$ micromamba install --quiet --channel anaconda-client-test --channel conda-forge --yes "anaconda-client=1.12.0rc1"
(base) mambauser@4999fa799ae3:/tmp$ anaconda --version
anaconda Command line client (version 1.12.0rc1)
(base) mambauser@4999fa799ae3:/tmp$ anaconda --help
usage: anaconda [-h] [--disable-ssl-warnings] [--show-traceback] [-v] [-q] [-t TOKEN] [-s SITE] [-V]  ...

Anaconda repository command line manager.

options:
  -h, --help            show this help message and exit
  -V, --version         show program's version number and exit

output:
  --disable-ssl-warnings
                        Disable SSL warnings (default: False)
  --show-traceback      Show the full traceback for chalmers user errors (default: False)
  -v, --verbose         print debug information on the console
  -q, --quiet           Only show warnings or errors on the console

anaconda-client options:
  -t TOKEN, --token TOKEN
                        Authentication token to use. May be a token or a path to a file containing a token
  -s SITE, --site SITE  select the anaconda-client site to use

Commands:
  
    auth                Manage Authorization Tokens
    label               Manage your Anaconda repository labels
    channel             [DEPRECATED in favor of label] Manage your Anaconda repository channels
    config              Anaconda client configuration
    copy                Copy packages from one account to another
    download            Download notebooks from your Anaconda repository
    groups              Manage Groups
    login               Authenticate a user
    logout              Log out from your Anaconda repository
    move                Move packages between labels
    notebook            Interact with notebooks in your Anaconda repository
    package             Package utils
    remove              Remove an object from your Anaconda repository. Must refer to the formal package name as it appears in the URL of the package. Also use anaconda show <USERNAME> to
                        see list of package names. Example: anaconda remove continuumio/empty-example-notebook
    search              Search in your Anaconda repository
    show                Show information about an object
    upload              Upload packages to your Anaconda repository
    whoami              Print the information of the current user
(base) mambauser@4999fa799ae3:/tmp$
```

and so `v1.12.0` will remove the need to manually set `CONDA_ROOT`.

Of course alternatively to setting both channels by hand on the command line we could have done

```console
(base) mambauser@4999fa799ae3:/tmp$ echo -e "channels:\n  - anaconda-client-test\n  - conda-forge" > ~/.mambarc
(base) mambauser@4999fa799ae3:/tmp$ cat ~/.mambarc
channels:
  - anaconda-client-test
  - conda-forge
(base) mambauser@4999fa799ae3:/tmp$ micromamba install --quiet --yes "anaconda-client=1.12.0rc1"
```

> Do you have other channels configured for mamba to work from?

No, the example was using a Docker image with no defaults.

**Comment by matthewfeickert** [comment]
@AlbertDeFusco With the release of https://github.com/Anaconda-Platform/anaconda-client/releases/tag/1.12.0 today I think this issue can probably be closed, unless @baleland had other outstanding issues.
