### ISSUE TITLE
anaconda-client >= 1.12.0 needs to require python >= 3.8

### ISSUE THREAD

**Issue by wuillaum** [Anaconda-Platform/anaconda-client#678]
Users on python 3.6 and 3.7 are still able to download anaconda-client 1.12.0 
```
anaconda-client 1.12.0 pyhd8ed1ab_0
-----------------------------------
file name   : anaconda-client-1.12.0-pyhd8ed1ab_0.conda
name        : anaconda-client
version     : 1.12.0
build       : pyhd8ed1ab_0
build number: 0
size        : 72 KB
license     : BSD-3-Clause
subdir      : noarch
url         : https://conda.anaconda.org/conda-forge/noarch/anaconda-client-1.12.0-pyhd8ed1ab_0.conda
md5         : 0bc9d7f17f6f946c66f896bda5c7ee6b
timestamp   : 2023-07-18 11:12:29 UTC
dependencies: 
  - anaconda-project >=0.9.1
  - clyent >=1.2.0
  - conda-package-handling >=1.7.3
  - defusedxml >=0.7.1
  - nbformat >=4.4.0
  - pillow >=8.2
  - python >=3.6           <------------------- PROBLEM
  - python-dateutil >=2.6.1
  - pytz >=2021.3
  - pyyaml >=3.12
  - requests >=2.20.0
  - requests-toolbelt >=0.9.1
  - setuptools >=58.0.4
  - six >=1.15.0
  - tqdm >=4.56.0
  - urllib3 >=1.26.4,<2.0.0a0
```

`1.12.0` does not support python 3.6 or 3.7, as the walrus operator is used (3.8+).

```
python
Python 3.7.15 (default, Nov 24 2022, 21:12:53) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from binstar_client.scripts.cli import main
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/<redacted>/anaconda/lib/python3.7/site-packages/binstar_client/__init__.py", line 23, in <module>
    from .mixins.channels import ChannelsMixin
  File "/<redacted>/anaconda/lib/python3.7/site-packages/binstar_client/mixins/channels.py", line 9, in <module>
    from binstar_client.utils import jencode
  File "/<redacted>/anaconda/lib/python3.7/site-packages/binstar_client/utils/__init__.py", line 13, in <module>
    from .config import (
  File "/<redacted>/anaconda/lib/python3.7/site-packages/binstar_client/utils/config.py", line 21, in <module>
    from binstar_client.utils import conda
  File "/<redacted>/anaconda/lib/python3.7/site-packages/binstar_client/utils/conda.py", line 52
    if command := os.environ.get('CONDA_EXE', ''):
                ^
SyntaxError: invalid syntax
```

**Comment by matthewfeickert** [comment]
@wuillaum :wave: I'm not a maintainer, but I agree this should be fixed so please see https://github.com/conda-forge/anaconda-client-feedstock/pull/44 and feel free to add your review.

**Comment by matthewfeickert** [comment]
@wuillaum now that https://github.com/conda-forge/anaconda-client-feedstock/pull/44 has been merged can you wait an hour to make sure deployment happens and then check to make sure that if you're on a Python older than Python 3.8 you can't install `anaconda-client` `v1.12.0`?

**Comment by wuillaum** [comment]
@matthewfeickert unfortunately it looks like there is still a build that will get installed if you're on 3.6/3.7

```
anaconda-client 1.12.0 pyhd8ed1ab_0
-----------------------------------
file name   : anaconda-client-1.12.0-pyhd8ed1ab_0.conda
name        : anaconda-client
version     : 1.12.0
build       : pyhd8ed1ab_0
build number: 0
size        : 72 KB
license     : BSD-3-Clause
subdir      : noarch
url         : https://conda.anaconda.org/conda-forge/noarch/anaconda-client-1.12.0-pyhd8ed1ab_0.conda
md5         : 0bc9d7f17f6f946c66f896bda5c7ee6b
timestamp   : 2023-07-18 11:12:29 UTC
dependencies: 
  - anaconda-project >=0.9.1
  - clyent >=1.2.0
  - conda-package-handling >=1.7.3
  - defusedxml >=0.7.1
  - nbformat >=4.4.0
  - pillow >=8.2
  - python >=3.6                           <---------------------------------- python 3.6
  - python-dateutil >=2.6.1
  - pytz >=2021.3
  - pyyaml >=3.12
  - requests >=2.20.0
  - requests-toolbelt >=0.9.1
  - setuptools >=58.0.4
  - six >=1.15.0
  - tqdm >=4.56.0
  - urllib3 >=1.26.4,<2.0.0a0
```

**Comment by matthewfeickert** [comment]
> unfortunately it looks like there is still a build that will get installed if you're on 3.6/3.7

This might be related to https://github.com/conda-forge/anaconda-client-feedstock/pull/44#issuecomment-1666221528

**Comment by wuillaum** [comment]
nice! Thanks for taking care of this @matthewfeickert
